import type { Metadata } from "next";
import { EB_Garamond, VT323, Coming_Soon } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const eB_Garamond = EB_Garamond({ subsets: ["latin"] });
const vT323 = VT323({
  subsets: ["latin"],
  variable: "--font-VT323",
  weight: "400",
});
const coming_Soon = Coming_Soon({
  subsets: ["latin"],
  variable: "--font-Coming_Soon",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Sami Adel | Dentist & Js Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${eB_Garamond.className} ${vT323.variable} ${coming_Soon.variable}`}
      >
        <div className="opacity-40" id="stars"></div>
        <div className="opacity-60" id="stars2"></div>
        <div className="opacity-40" id="stars3"></div>
        <Header />
        {children}
      </body>
    </html>
  );
}
